<?php


/**
 * @file
 * Hooks and callbacks for this module.
 */

/**
 * Implements hook_menu().
 * Drupal menus allow urls to be used as function calls, giving Drupal gets much
 * of its power and flexibillty.
 * See https://api.drupal.org/api/drupal/modules!system!system.api.php/function/hook_menu/7
 */
function islandora_livingresearchlab_menu() {
  $items = array();
  $items['admin/islandora/solution_pack_config/livingresearchlab'] => array(
    'title' => 'DSU Living Research Lab Solution Pack',
    'description' => 'Configure the Living Research Lab solution pack.',
    'page callback' => 'drupal_get_form',
    'access arguments' => array('administer site configuration'),
    'page arguments' => array('islandora_livingresearchlab_admin'),
    'file' => 'includes/islandora_livingresearchlab.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implements hook_theme().
 *
 */
function islandora_livingresearchlab_theme($existing, $type, $theme, $path) {
  return array(
    'islandora_livingresearchlab' => array(
      'template' => 'theme/islandora-livingresearchlab',
      'file' => 'theme/theme.inc',
      'pattern' => 'islandora_livingresearchlab__',
      'variables' => array('object' => NULL),
    ),
    'islandora_lrl_datasession' => array(
      'template' => 'theme/islandora-ltl-datasession',
      'pattern' => 'islandora_ltl_datasession__',
      'variables' => array('object' => NULL),
    ),
    'islandora_lrl_experiment' => array(
      'template' => 'theme/islandora-ltl-experiment',
      'pattern' => 'islandora_lrl_experiment__',
      'variables' => array('object' => NULL),
    ),
    'islandora_lrl_mouse' => array(
      'template' => 'theme/islandora-ltl-mouse',
      'pattern' => 'islandora_lrl_mouse__',
      'variables' => array('object' => NULL),
    ),
    'islandora_lrl_birth' => array(
      'template' => 'theme/islandora-ltl-birth',
      'pattern' => 'islandora_lrl_birth__',
      'variables' => array('object' => NULL),
    ),
    'islandora_lrl_protocol' => array(
      'template' => 'theme/islandora-ltl-protocol',
      'pattern' => 'islandora_lrl_protocol__',
      'variables' => array('object' => NULL),
    ),
    'islandora_lrl_publication' => array(
      'template' => 'theme/islandora-ltl-publication',
      'pattern' => 'islandora_lrl_publication__',
      'variables' => array('object' => NULL),
    ),

  );
}


/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_livingresearchlab_islandora_livingresearchlab_islandora_view_object($object) {
  $output = theme('islandora_livingresearchlab', array('islandora_object' => $object));
  return array('' => $output);
}


function islandora_livingresearchlab_islandora_livingresearchlab_datasessionCModel_islandora_view_object($object) {
  $output = theme('lrl_datasession', array('islandora_object' => $object));
  return array('' => $output);
}

function islandora_livingresearchlab_islandora_livingresearchlab_experimentCModel_islandora_view_object($object) {
  $output = theme('lrl_experiment', array('islandora_object' => $object));
  return array('' => $output);
}

function islandora_livingresearchlab_islandora_livingresearchlab_mouseCModel_islandora_view_object($object) {
  $output = theme('lrl_mouse', array('islandora_object' => $object));
  return array('' => $output);
}

// function islandora_livingresearchlab_islandora_livingresearchlab_protocolCModel_islandora_view_object($object) {
//   $output = theme('lrl_procotol', array('islandora_object' => $object));
//   return array('' => $output);
// }

// function islandora_livingresearchlab_islandora_livingresearchlab_publicationCModel_islandora_view_object($object) {
//   $output = theme('lrl_publication', array('islandora_object' => $object));
//   return array('' => $output);
// }


/**
 * Implements hook_islandora_ingest_steps().
 * This hook adds a single ingest step, but more could be added as seperate entries.
 */

// no upload 2014-08-14
// function islandora_livingresearchlab_islandora_livingresearchlabCModel_islandora_ingest_steps(array $configuration) {
//   return array(
//     'islandora_livingresearchlab_file_upload' => array(
//       'weight' => 10,
//       'type' => 'form',
//       'form_id' => 'islandora_livingresearchlab_upload_form',
//       'module' => 'islandora_livingresearchlab',
//       'file' => 'includes/islandora_livingresearchlab_upload.form.inc'
//     )
//   );
// }


/**
 * Implements hook_CMODEL_PID_islandora_object_ingested().
 * This hook tells Islandora what to do with the object once it has been ingested.
 * In this case the raw text has been uploaded so we'll be in a position to
 * use that as input for our derived datastreams. The function
 * islandora_livingresearchlab_create_all_derivatives will be called with a refrence to the
 * as yet uningested object.
 */

// no upload 2014-08-14
// function islandora_livingresearchlab_islandora_livingresearchlabCModel_islandora_object_ingested($object) {
//   module_load_include('inc', 'islandora_livingresearchlab', 'includes/derivatives');
//   islandora_livingresearchlab_create_all_derivatives($object);
// }

/**
 * Implements hook_islandora_xml_form_builder_forms().
 * This hook makes a predefined ingest form for ingest.
 */
function islandora_livingresearchlab_islandora_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'islandora_livingresearchlab');

  return array(

    'DSU Data Session DwC' => array(
      'form_file' => "$module_path/xml/forms/DataSession_dwc.xml",
    ),
    'DSU Experiment DwC' => array(
      'form_file' => "$module_path/xml/forms/Experiment_dwc.xml",
    ),
    'DSU Mouse DwC' => array(
      'form_file' => "$module_path/xml/forms/Mouse_dwc.xml",
    ),
    'DSU Protocol DwC' => array(
      'form_file' => "$module_path/xml/forms/Protocol_dwc.xml",
    ),
    'DSU Publication MODS' => array(
      'form_file' => "$module_path/xml/forms/Publication_MODS.xml",
    ),
  );
}


function islandora_livingresearchlab_xml_form_builder_get_self_transforms() {
  $module_path = drupal_get_path('module', 'islandora_livingresearchlab');
  return array(
    'dwcclassoccurrence2dc.xsl' => "$module_path/xsl/dwcclassoccurrence2dc.xsl",
    'mods_to_dc.xsl' => "$module_path/xsl/mods_to_dc.xsl",
    'cleanup_mods.xsl' => "$module_path/xsl/cleanup_mods.xsl"
  );
}


/**
 * Implements hook_islandora_content_model_forms_form_associations().
 * This hook associated our form with our content model.  Any time we try to ingest
 * an object with the islandora:livingresearchlabCModel content model, we will see this form
 * allowing us to supply relevant metadata.
 */
function islandora_livingresearchlab_islandora_content_model_forms_form_associations() {
  $module_path = drupal_get_path('module', 'islandora_livingresearchlab');

  return array(

    'islandora_livingresearchlab_datasession_dwc_form' => array(
      'content_model' => 'islandora:livingresearchlab_datasessionCModel',
      'form_name' => 'DSU Data Session DwC',
      'dsid' => 'DWC',
      'title_field' => array(
        'dwc_fields_datasession',
        'occurrence1',
        'occurrenceid1'
      ),
      'transform' => 'dwcclassoccurrence2dc.xsl',
      'self_transform' => 'cleanup_mods.xsl',
      'template' => FALSE,
    ),
    'islandora_livingresearchlab_experiment_dwc_form' => array(
      'content_model' => 'islandora:livingresearchlab_experimentCModel',
      'form_name' => 'DSU Experiment DwC',
      'dsid' => 'DWC',
      'title_field' => array(
        'dwc_fields_experiment',
        'occurrence',
        'occurrenceid'
      ),
      'transform' => 'dwcclassoccurrence2dc.xsl',
      'self_transform' => 'cleanup_mods.xsl',
      'template' => FALSE,
    ),
    'islandora_livingresearchlab_mouse_dwc_form' => array(
      'content_model' => 'islandora:livingresearchlab_mouseCModel',
      'form_name' => 'DSU Mouse DwC',
      'dsid' => 'DWC',
      'title_field' => array('dwc_fields_mouse', 'occurrence1', 'occurrenceid'),
      'transform' => 'dwcclassoccurrence2dc.xsl',
      'self_transform' => 'cleanup_mods.xsl',
      'template' => FALSE,
    ),
    'islandora_livingresearchlab_protocol_dwc_form' => array(
      'content_model' => 'islandora:sp_pdf',
      'form_name' => 'DSU Protocol DwC',
      'dsid' => 'DWC',
      'title_field' => array(
        'dwc_fields_protocol',
        'occurrence',
        'occurrenceid'
      ),
      'transform' => 'dwcclassoccurrence2dc.xsl',
      'self_transform' => 'cleanup_mods.xsl',
      'template' => FALSE,
    ),
    'islandora_livingresearchlab_publication_dwc_form' => array(
      'content_model' => 'islandora:sp_pdf',
      'form_name' => 'DSU Publication MODS',
      'dsid' => 'MODS',
      'title_field' => array('titleInfo', 'title'),
      'transform' => 'mods_to_dc.xsl',
      'self_transform' => 'cleanup_mods.xsl',
      'template' => FALSE,
    ),
  );
}


/**
 * Implements hook_islandora_required_objects().
 * This hook ingests a very basic content model.  It is run when the module is
 * first installed.
 */
function islandora_livingresearchlab_islandora_required_objects(IslandoraTuque $connection) {

  $module_path = drupal_get_path('module', 'islandora_livingresearchlab');


  /** Data Session CModel */
  $livingresearchlab_datasession_content_model = $connection->repository->constructObject('islandora:livingresearchlab_datasessionCModel');
  $livingresearchlab_datasession_content_model->owner = 'fedoraAdmin';
  $livingresearchlab_datasession_content_model->label = 'Islandora Living Research Lab Data Session Content Model';
  $livingresearchlab_datasession_content_model->models = 'fedora-system:ContentModel-3.0';

  $datastream = $livingresearchlab_datasession_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_livingresearchlab_datasession_ds_composite_model.xml", FALSE);
  $livingresearchlab_datasession_content_model->ingestDatastream($datastream);

  /** Experiment CModel */
  $livingresearchlab_experiment_content_model = $connection->repository->constructObject('islandora:livingresearchlab_experimentCModel');
  $livingresearchlab_experiment_content_model->owner = 'fedoraAdmin';
  $livingresearchlab_experiment_content_model->label = 'Islandora Living Research Lab Experiment Content Model';
  $livingresearchlab_experiment_content_model->models = 'fedora-system:ContentModel-3.0';

  $datastream = $livingresearchlab_experiment_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_livingresearchlab_experiment_ds_composite_model.xml", FALSE);
  $livingresearchlab_experiment_content_model->ingestDatastream($datastream);

  /** Mouse CModel */
  $livingresearchlab_mouse_content_model = $connection->repository->constructObject('islandora:livingresearchlab_mouseCModel');
  $livingresearchlab_mouse_content_model->owner = 'fedoraAdmin';
  $livingresearchlab_mouse_content_model->label = 'Islandora Living Research Lab Mouse Content Model';
  $livingresearchlab_mouse_content_model->models = 'fedora-system:ContentModel-3.0';

  $datastream = $livingresearchlab_mouse_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_livingresearchlab_mouse_ds_composite_model.xml", FALSE);
  $livingresearchlab_mouse_content_model->ingestDatastream($datastream);


// // * Protocol CModel
//  $livingresearchlab_protocol_content_model = $connection->repository->constructObject('islandora:livingresearchlab_protocolCModel');
//  $livingresearchlab_protocol_content_model->owner = 'fedoraAdmin';
//  $livingresearchlab_protocol_content_model->label = 'Islandora Living Research Lab Protocol Content Model';
//  $livingresearchlab_protocol_content_model->models = 'fedora-system:ContentModel-3.0';

//   $datastream =$livingresearchlab_protocol_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
//   $datastream->label = 'DS-COMPOSITE-MODEL';
//   $datastream->mimetype = 'text/xml';
//   $datastream->setContentFromFile("$module_path/xml/islandora_livingresearchlab_protocol_ds_composite_model.xml", FALSE);
//  $livingresearchlab_protocol_content_model->ingestDatastream($datastream);


// // * Publication CModel  
//  $livingresearchlab_publication_content_model = $connection->repository->constructObject('islandora:livingresearchlab_publicationCModel');
//  $livingresearchlab_publication_content_model->owner = 'fedoraAdmin';
//  $livingresearchlab_publication_content_model->label = 'Islandora Living Research Lab Publication Content Model';
//  $livingresearchlab_publication_content_model->models = 'fedora-system:ContentModel-3.0';

//   $datastream =$livingresearchlab_publication_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
//   $datastream->label = 'DS-COMPOSITE-MODEL';
//   $datastream->mimetype = 'text/xml';
//   $datastream->setContentFromFile("$module_path/xml/islandora_livingresearchlab_publication_ds_composite_model.xml", FALSE);
//  $livingresearchlab_publication_content_model->ingestDatastream($datastream);


  /** DATASESSION root collection */
  $datasessions_collection = $connection->repository->constructObject('islandora:datasessions_collection');
  $datasessions_collection->owner = 'fedoraAdmin';
  $datasessions_collection->label = 'Islandora Living Research Lab Data Sessions Collection';
  $datasessions_collection->models = 'islandora:collectionCModel';
  $datasessions_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');

  $datastream = $datasessions_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $datastream->label = 'Collection policy';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/collection_policy/islandora_livingresearchlab_datasessions_collection_policy.xml", FALSE);
  $datasessions_collection->ingestDatastream($datastream);

  $datastream = $datasessions_collection->constructDatastream('TN', 'M');
  $datastream->label = 'Thumbnail';
  $datastream->mimetype = 'image/png';
  $datastream->setContentFromFile("$module_path/images/datasessions.png", FALSE);
  $datasessions_collection->ingestDatastream($datastream);


  /** EXPERIMENTS root collection */
  $experiments_collection = $connection->repository->constructObject('islandora:experiments_collection');
  $experiments_collection->owner = 'fedoraAdmin';
  $experiments_collection->label = 'Islandora Living Research Lab Experiments Collection';
  $experiments_collection->models = 'islandora:collectionCModel';
  $experiments_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');

  $datastream = $experiments_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $datastream->label = 'Collection policy';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/collection_policy/islandora_livingresearchlab_experiments_collection_policy.xml", FALSE);
  $experiments_collection->ingestDatastream($datastream);

  $datastream = $experiments_collection->constructDatastream('TN', 'M');
  $datastream->label = 'Thumbnail';
  $datastream->mimetype = 'image/png';
  $datastream->setContentFromFile("$module_path/images/experiments.png", FALSE);
  $experiments_collection->ingestDatastream($datastream);

  /** MICE root collection */
  $mice_collection = $connection->repository->constructObject('islandora:mice_collection');
  $mice_collection->owner = 'fedoraAdmin';
  $mice_collection->label = 'Islandora Living Research Lab Mice Collection';
  $mice_collection->models = 'islandora:collectionCModel';
  $mice_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');

  $datastream = $mice_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $datastream->label = 'Collection policy';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/collection_policy/islandora_livingresearchlab_mice_collection_policy.xml", FALSE);
  $mice_collection->ingestDatastream($datastream);

  $datastream = $mice_collection->constructDatastream('TN', 'M');
  $datastream->label = 'Thumbnail';
  $datastream->mimetype = 'image/png';
  $datastream->setContentFromFile("$module_path/images/mice.png", FALSE);
  $mice_collection->ingestDatastream($datastream);

  /** PROTOCOLS root collection */
  $protocols_collection = $connection->repository->constructObject('islandora:protocols_collection');
  $protocols_collection->owner = 'fedoraAdmin';
  $protocols_collection->label = 'Islandora Living Research Lab Protocols Collection';
  $protocols_collection->models = 'islandora:collectionCModel';
  $protocols_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');

  $datastream = $protocols_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $datastream->label = 'Collection policy';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/collection_policy/islandora_livingresearchlab_protocols_collection_policy.xml", FALSE);
  $protocols_collection->ingestDatastream($datastream);

  $datastream = $protocols_collection->constructDatastream('TN', 'M');
  $datastream->label = 'Thumbnail';
  $datastream->mimetype = 'image/png';
  $datastream->setContentFromFile("$module_path/images/protocols.png", FALSE);
  $protocols_collection->ingestDatastream($datastream);

  /** PUBLICATIONS root collection */
  $publications_collection = $connection->repository->constructObject('islandora:publications_collection');
  $publications_collection->owner = 'fedoraAdmin';
  $publications_collection->label = 'Islandora Living Research Lab Publications Collection';
  $publications_collection->models = 'islandora:collectionCModel';
  $publications_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');

  $datastream = $publications_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $datastream->label = 'Collection policy';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/collection_policy/islandora_livingresearchlab_publications_collection_policy.xml", FALSE);
  $publications_collection->ingestDatastream($datastream);

  $datastream = $publications_collection->constructDatastream('TN', 'M');
  $datastream->label = 'Thumbnail';
  $datastream->mimetype = 'image/png';
  $datastream->setContentFromFile("$module_path/images/publications.png", FALSE);
  $publications_collection->ingestDatastream($datastream);

  return array(
    'islandora_livingresearchlab' => array(
      'title' => 'Islandora Living Research Lab Solution Pack',
      'objects' => array(
        $livingresearchlab_datasession_content_model,
        $livingresearchlab_experiment_content_model,
        $livingresearchlab_mouse_content_model,
        $datasessions_collection,
        $experiments_collection,
        $mice_collection,
        $protocols_collection,
        $publications_collection,
      ),
    ),
  );
}
